name: quantdev
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - scipy
  - matplotlib
  - scikit-learn
  - jupyterlab
  - pip
  - pip:
      - aiohttp
      - tqdm
      - polars
      - pyarrow
      - lxml
      - aiofiles
      - asyncio
      - beautifulsoup4
